language: C



compiler:

  - gcc

before_install:

  - sudo apt-get update
  
install:

  - echo "Reached Install Section"

script:

  - echo "Reached Script Section - Hello"
  - gcc calculator.c -o output
  - ./output
